/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 scifi_girl.glb 
Author: patrix (https://sketchfab.com/patrix)
License: CC-BY-NC-SA-4.0 (http://creativecommons.org/licenses/by-nc-sa/4.0/)
Source: https://sketchfab.com/3d-models/scifi-girl-v01-96340701c2ed4d37851c7d9109eee9c0
Title: Scifi Girl v.01
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/scifi-girl.glb')
  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={0.1}>
        <mesh geometry={nodes.Object_2.geometry} material={materials.body} />
        <mesh geometry={nodes.Object_3.geometry} material={materials.cloth} />
        <mesh geometry={nodes.Object_4.geometry} material={materials.eyelash} />
        <mesh geometry={nodes.Object_5.geometry} material={materials.eyes_inner} />
        <mesh geometry={nodes.Object_6.geometry} material={materials.eyes_outer} />
        <mesh geometry={nodes.Object_7.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_8.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_9.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_10.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_11.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_12.geometry} material={materials.material} />
        <mesh geometry={nodes.Object_13.geometry} material={materials.ground} />
        <mesh geometry={nodes.Object_14.geometry} material={materials.hair_inner} />
        <mesh geometry={nodes.Object_15.geometry} material={materials.hair_outer} />
        <mesh geometry={nodes.Object_16.geometry} material={materials.light} />
        <mesh geometry={nodes.Object_17.geometry} material={materials.ring} />
        <mesh geometry={nodes.Object_18.geometry} material={materials.tear} />
      </group>
    </group>
  )
}

useGLTF.preload('/scifi_girl.glb')
